
name: Latest blog post workflow
on:
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 
        with:
          max_post_count: "4"
          feed_list: ""
